/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as VendorsNewRouteImport } from './routes/vendors/new'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors/$vendorId'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as StoresNewRouteImport } from './routes/stores/new'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as VendorsVendorIdEditRouteImport } from './routes/vendors/$vendorId/edit'
import { Route as VendorsVendorIdDeleteRouteImport } from './routes/vendors/$vendorId/delete'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId/edit'
import { Route as UsersUserIdDeleteRouteImport } from './routes/users/$userId/delete'
import { Route as StoresStoreIdEditRouteImport } from './routes/stores/$storeId/edit'
import { Route as StoresStoreIdDeleteRouteImport } from './routes/stores/$storeId/delete'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsNewRoute = VendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdEditRoute = VendorsVendorIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VendorsVendorIdRoute,
} as any)
const VendorsVendorIdDeleteRoute = VendorsVendorIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => VendorsVendorIdRoute,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdDeleteRoute = UsersUserIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const StoresStoreIdEditRoute = StoresStoreIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StoresStoreIdRoute,
} as any)
const StoresStoreIdDeleteRoute = StoresStoreIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => StoresStoreIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/new': typeof StoresNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/vendors/$vendorId': typeof VendorsVendorIdRouteWithChildren
  '/vendors/new': typeof VendorsNewRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/stores/$storeId/delete': typeof StoresStoreIdDeleteRoute
  '/stores/$storeId/edit': typeof StoresStoreIdEditRoute
  '/users/$userId/delete': typeof UsersUserIdDeleteRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/vendors/$vendorId/delete': typeof VendorsVendorIdDeleteRoute
  '/vendors/$vendorId/edit': typeof VendorsVendorIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/new': typeof StoresNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/vendors/$vendorId': typeof VendorsVendorIdRouteWithChildren
  '/vendors/new': typeof VendorsNewRoute
  '/products': typeof ProductsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/users': typeof UsersIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/stores/$storeId/delete': typeof StoresStoreIdDeleteRoute
  '/stores/$storeId/edit': typeof StoresStoreIdEditRoute
  '/users/$userId/delete': typeof UsersUserIdDeleteRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/vendors/$vendorId/delete': typeof VendorsVendorIdDeleteRoute
  '/vendors/$vendorId/edit': typeof VendorsVendorIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/new': typeof StoresNewRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/vendors/$vendorId': typeof VendorsVendorIdRouteWithChildren
  '/vendors/new': typeof VendorsNewRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/stores/$storeId/delete': typeof StoresStoreIdDeleteRoute
  '/stores/$storeId/edit': typeof StoresStoreIdEditRoute
  '/users/$userId/delete': typeof UsersUserIdDeleteRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/vendors/$vendorId/delete': typeof VendorsVendorIdDeleteRoute
  '/vendors/$vendorId/edit': typeof VendorsVendorIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/settings'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeId'
    | '/stores/new'
    | '/users/$userId'
    | '/vendors/$vendorId'
    | '/vendors/new'
    | '/products/'
    | '/stores/'
    | '/users/'
    | '/vendors/'
    | '/stores/$storeId/delete'
    | '/stores/$storeId/edit'
    | '/users/$userId/delete'
    | '/users/$userId/edit'
    | '/vendors/$vendorId/delete'
    | '/vendors/$vendorId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/settings'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeId'
    | '/stores/new'
    | '/users/$userId'
    | '/vendors/$vendorId'
    | '/vendors/new'
    | '/products'
    | '/stores'
    | '/users'
    | '/vendors'
    | '/stores/$storeId/delete'
    | '/stores/$storeId/edit'
    | '/users/$userId/delete'
    | '/users/$userId/edit'
    | '/vendors/$vendorId/delete'
    | '/vendors/$vendorId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/settings'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeId'
    | '/stores/new'
    | '/users/$userId'
    | '/vendors/$vendorId'
    | '/vendors/new'
    | '/products/'
    | '/stores/'
    | '/users/'
    | '/vendors/'
    | '/stores/$storeId/delete'
    | '/stores/$storeId/edit'
    | '/users/$userId/delete'
    | '/users/$userId/edit'
    | '/vendors/$vendorId/delete'
    | '/vendors/$vendorId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  StoresStoreIdRoute: typeof StoresStoreIdRouteWithChildren
  StoresNewRoute: typeof StoresNewRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  VendorsVendorIdRoute: typeof VendorsVendorIdRouteWithChildren
  VendorsNewRoute: typeof VendorsNewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/new': {
      id: '/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof VendorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId/edit': {
      id: '/vendors/$vendorId/edit'
      path: '/edit'
      fullPath: '/vendors/$vendorId/edit'
      preLoaderRoute: typeof VendorsVendorIdEditRouteImport
      parentRoute: typeof VendorsVendorIdRoute
    }
    '/vendors/$vendorId/delete': {
      id: '/vendors/$vendorId/delete'
      path: '/delete'
      fullPath: '/vendors/$vendorId/delete'
      preLoaderRoute: typeof VendorsVendorIdDeleteRouteImport
      parentRoute: typeof VendorsVendorIdRoute
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/delete': {
      id: '/users/$userId/delete'
      path: '/delete'
      fullPath: '/users/$userId/delete'
      preLoaderRoute: typeof UsersUserIdDeleteRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/stores/$storeId/edit': {
      id: '/stores/$storeId/edit'
      path: '/edit'
      fullPath: '/stores/$storeId/edit'
      preLoaderRoute: typeof StoresStoreIdEditRouteImport
      parentRoute: typeof StoresStoreIdRoute
    }
    '/stores/$storeId/delete': {
      id: '/stores/$storeId/delete'
      path: '/delete'
      fullPath: '/stores/$storeId/delete'
      preLoaderRoute: typeof StoresStoreIdDeleteRouteImport
      parentRoute: typeof StoresStoreIdRoute
    }
  }
}

interface StoresStoreIdRouteChildren {
  StoresStoreIdDeleteRoute: typeof StoresStoreIdDeleteRoute
  StoresStoreIdEditRoute: typeof StoresStoreIdEditRoute
}

const StoresStoreIdRouteChildren: StoresStoreIdRouteChildren = {
  StoresStoreIdDeleteRoute: StoresStoreIdDeleteRoute,
  StoresStoreIdEditRoute: StoresStoreIdEditRoute,
}

const StoresStoreIdRouteWithChildren = StoresStoreIdRoute._addFileChildren(
  StoresStoreIdRouteChildren,
)

interface UsersUserIdRouteChildren {
  UsersUserIdDeleteRoute: typeof UsersUserIdDeleteRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdDeleteRoute: UsersUserIdDeleteRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

interface VendorsVendorIdRouteChildren {
  VendorsVendorIdDeleteRoute: typeof VendorsVendorIdDeleteRoute
  VendorsVendorIdEditRoute: typeof VendorsVendorIdEditRoute
}

const VendorsVendorIdRouteChildren: VendorsVendorIdRouteChildren = {
  VendorsVendorIdDeleteRoute: VendorsVendorIdDeleteRoute,
  VendorsVendorIdEditRoute: VendorsVendorIdEditRoute,
}

const VendorsVendorIdRouteWithChildren = VendorsVendorIdRoute._addFileChildren(
  VendorsVendorIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  StoresStoreIdRoute: StoresStoreIdRouteWithChildren,
  StoresNewRoute: StoresNewRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  VendorsVendorIdRoute: VendorsVendorIdRouteWithChildren,
  VendorsNewRoute: VendorsNewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
