/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StoresStoreSlugRouteImport } from './routes/stores/$storeSlug'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountPreferencesRouteImport } from './routes/account/preferences'
import { Route as AccountPasswordRouteImport } from './routes/account/password'
import { Route as AccountHistoryRouteImport } from './routes/account/history'
import { Route as AccountFavoritesRouteImport } from './routes/account/favorites'
import { Route as AccountDeleteRouteImport } from './routes/account/delete'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreSlugRoute = StoresStoreSlugRouteImport.update({
  id: '/stores/$storeSlug',
  path: '/stores/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/account/history',
  path: '/account/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/account/favorites',
  path: '/account/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/account': typeof AccountIndexRoute
  '/products': typeof ProductsIndexRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/delete'
    | '/account/favorites'
    | '/account/history'
    | '/account/password'
    | '/account/preferences'
    | '/account/profile'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeSlug'
    | '/account/'
    | '/products/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/delete'
    | '/account/favorites'
    | '/account/history'
    | '/account/password'
    | '/account/preferences'
    | '/account/profile'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeSlug'
    | '/account'
    | '/products'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/delete'
    | '/account/favorites'
    | '/account/history'
    | '/account/password'
    | '/account/preferences'
    | '/account/profile'
    | '/products/$productId'
    | '/reset-password/$token'
    | '/stores/$storeSlug'
    | '/account/'
    | '/products/'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  StoresStoreSlugRoute: typeof StoresStoreSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeSlug': {
      id: '/stores/$storeSlug'
      path: '/stores/$storeSlug'
      fullPath: '/stores/$storeSlug'
      preLoaderRoute: typeof StoresStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/history': {
      id: '/account/history'
      path: '/account/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountProfileRoute: AccountProfileRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  StoresStoreSlugRoute: StoresStoreSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
